export const COUNTRIES = [{ name: "Afghanistan", id: 1 },
{ name: "Albania", id: 3 },
{ name: "Algeria", id: 4 },
{ name: "American Samoa", id: 239 },
{ name: "American Virgin Islands", id: 234 },
{ name: "Andorra", id: 5 },
{ name: "Angola", id: 6 },
{ name: "Anguilla", id: 232 },
{ name: "Antigua and Barbuda", id: 7 },
{ name: "Argentina", id: 9 },
{ name: "Armenia", id: 10 },
{ name: "Aruba", id: 233 },
{ name: "Australia", id: 12 },
{ name: "Austria", id: 127 },
{ name: "Azerbaijan", id: 13 },
{ name: "Bahamas", id: 14 },
{ name: "Bahrain", id: 15 },
{ name: "Bangladesh", id: 16 },
{ name: "Barbados", id: 17 },
{ name: "Belarus", id: 18 },
{ name: "Belgium", id: 19 },
{ name: "Belize", id: 20 },
{ name: "Benin", id: 21 },
{ name: "Bermuda", id: 211 },
{ name: "Bhutan", id: 22 },
{ name: "Bolivia", id: 23 },
{ name: "Bonaire", id: 269 },
{ name: "Bosnia-Herzegovina", id: 24 },
{ name: "Botsuana", id: 25 },
{ name: "Brazil", id: 26 },
{ name: "British Virgin Islands", id: 231 },
{ name: "Brunei Darussalam", id: 27 },
{ name: "Bulgaria", id: 28 },
{ name: "Burkina Faso", id: 29 },
{ name: "Burundi", id: 30 },
{ name: "Cambodia", id: 79 },
{ name: "Cameroon", id: 31 },
{ name: "Canada", id: 80 },
{ name: "Cape Verde", id: 32 },
{ name: "Cayman-Inseln", id: 229 },
{ name: "Central African Republic", id: 138 },
{ name: "Chad", id: 171 },
{ name: "Chile", id: 33 },
{ name: "China", id: 34 },
{ name: "Chinese Taipei (Taiwan)", id: 164 },
{ name: "Christmas Island", id: 248 },
{ name: "Colombia", id: 83 },
{ name: "Comoros", id: 35 },
{ name: "Congo", id: 85 },
{ name: "Cookinseln", id: 238 },
{ name: "Costa Rica", id: 36 },
{ name: "Cote d'Ivoire", id: 38 },
{ name: "Croatia", id: 37 },
{ name: "CSSR", id: 220 },
{ name: "Cuba", id: 88 },
{ name: "Curacao", id: 260 },
{ name: "Cyprus", id: 188 },
{ name: "Czech Republic", id: 172 },
{ name: "DDR", id: 222 },
{ name: "Denmark", id: 39 },
{ name: "Djibouti", id: 41 },
{ name: "Dominica", id: 42 },
{ name: "Dominican Republic", id: 43 },
{ name: "DR Congo", id: 193 },
{ name: "Ecuador", id: 44 },
{ name: "Egypt", id: 2 },
{ name: "El Salvador", id: 45 },
{ name: "England", id: 189 },
{ name: "Equatorial Guinea", id: 8 },
{ name: "Eritrea", id: 46 },
{ name: "Estonia", id: 47 },
{ name: "Eswatini", id: 162 },
{ name: "Ethiopia", id: 11 },
{ name: "Falkland Islands", id: 250 },
{ name: "Faroe Islands", id: 208 },
{ name: "Federated States of Micronesia", id: 111 },
{ name: "Fiji", id: 48 },
{ name: "Finland", id: 49 },
{ name: "France", id: 50 },
{ name: "French Guiana", id: 252 },
{ name: "Gabon", id: 51 },
{ name: "Georgia", id: 53 },
{ name: "Germany", id: 40 },
{ name: "Ghana", id: 54 },
{ name: "Gibraltar", id: 266 },
{ name: "Greece", id: 56 },
{ name: "Greenland", id: 243 },
{ name: "Grenada", id: 55 },
{ name: "Guadeloupe", id: 251 },
{ name: "Guam", id: 241 },
{ name: "Guatemala", id: 58 },
{ name: "Guernsey", id: 271 },
{ name: "Guinea", id: 59 },
{ name: "Guinea-Bissau", id: 60 },
{ name: "Guyana", id: 61 },
{ name: "Haiti", id: 62 },
{ name: "Honduras", id: 66 },
{ name: "Hongkong", id: 218 },
{ name: "Hungary", id: 178 },
{ name: "Iceland", id: 73 },
{ name: "India", id: 67 },
{ name: "Indonesia", id: 68 },
{ name: "Iran", id: 71 },
{ name: "Iraq", id: 70 },
{ name: "Ireland", id: 72 },
{ name: "Isle of Man", id: 270 },
{ name: "Israel", id: 74 },
{ name: "Italy", id: 75 },
{ name: "Jamaica", id: 76 },
{ name: "Japan", id: 77 },
{ name: "Jersey", id: 272 },
{ name: "Jordan", id: 78 },
{ name: "Jugoslawien (SFR)", id: 223 },
{ name: "Kazakhstan", id: 81 },
{ name: "Kenya", id: 82 },
{ name: "Kiribati", id: 246 },
{ name: "Korea, North", id: 86 },
{ name: "Korea, South", id: 87 },
{ name: "Kosovo", id: 244 },
{ name: "Kuwait", id: 89 },
{ name: "Kyrgyzstan", id: 90 },
{ name: "Laos", id: 91 },
{ name: "Latvia", id: 92 },
{ name: "Lebanon", id: 94 },
{ name: "Lesotho", id: 93 },
{ name: "Liberia", id: 95 },
{ name: "Libya", id: 96 },
{ name: "Liechtenstein", id: 97 },
{ name: "Lithuania", id: 98 },
{ name: "Luxembourg", id: 99 },
{ name: "Macao", id: 219 },
{ name: "Macedonia", id: 274 },
{ name: "Madagascar", id: 101 },
{ name: "Malawi", id: 102 },
{ name: "Malaysia", id: 103 },
{ name: "Maldives", id: 104 },
{ name: "Mali", id: 105 },
{ name: "Malta", id: 106 },
{ name: "Mariana Islands", id: 268 },
{ name: "Marshall Islands", id: 257 },
{ name: "Martinique", id: 207 },
{ name: "Mauritania", id: 108 },
{ name: "Mauritius", id: 109 },
{ name: "Mexico", id: 110 },
{ name: "Moldova", id: 112 },
{ name: "Monaco", id: 113 },
{ name: "Mongolia", id: 114 },
{ name: "Montenegro", id: 216 },
{ name: "Montserrat", id: 235 },
{ name: "Morocco", id: 107 },
{ name: "Mozambique", id: 115 },
{ name: "Myanmar", id: 116 },
{ name: "Namibia", id: 117 },
{ name: "Nauru", id: 118 },
{ name: "Nepal", id: 119 },
{ name: "Netherlands", id: 122 },
{ name: "Netherlands Antilles", id: 227 },
{ name: "Netherlands East India", id: 255 },
{ name: "Neukaledonien", id: 236 },
{ name: "New Zealand", id: 120 },
{ name: "Nicaragua", id: 121 },
{ name: "Niger", id: 123 },
{ name: "Nigeria", id: 124 },
{ name: "Niue", id: 261 },
{ name: "North Macedonia", id: 100 },
{ name: "Northern Ireland", id: 192 },
{ name: "Norway", id: 125 },
{ name: "Oman", id: 126 },
{ name: "Osttimor", id: 242 },
{ name: "Pakistan", id: 128 },
{ name: "Palästina", id: 240 },
{ name: "Palau", id: 129 },
{ name: "Panama", id: 130 },
{ name: "Papua New Guinea", id: 131 },
{ name: "Paraguay", id: 132 },
{ name: "People's republic of the Congo", id: 259 },
{ name: "Peru", id: 133 },
{ name: "Philippines", id: 134 },
{ name: "Poland", id: 135 },
{ name: "Portugal", id: 136 },
{ name: "Puerto Rico", id: 228 },
{ name: "Qatar", id: 137 },
{ name: "Réunion", id: 249 },
{ name: "Romania", id: 140 },
{ name: "Russia", id: 141 },
{ name: "Rwanda", id: 139 },
{ name: "Saarland", id: 263 },
{ name: "Saint-Martin", id: 267 },
{ name: "Samoa", id: 143 },
{ name: "San Marino", id: 144 },
{ name: "Sao Tome and Principe", id: 145 },
{ name: "Saudi Arabia", id: 146 },
{ name: "Scotland", id: 190 },
{ name: "Senegal", id: 149 },
{ name: "Serbia", id: 215 },
{ name: "Serbia and Montenegro", id: 150 },
{ name: "Seychelles", id: 151 },
{ name: "Sierra Leone", id: 152 },
{ name: "Singapore", id: 153 },
{ name: "Sint Maarten", id: 265 },
{ name: "Slovakia", id: 154 },
{ name: "Slovenia", id: 155 },
{ name: "Solomon Islands", id: 69 },
{ name: "Somalia", id: 156 },
{ name: "South Africa", id: 159 },
{ name: "Southern Sudan", id: 262 },
{ name: "Spain", id: 157 },
{ name: "Sri Lanka", id: 158 },
{ name: "St. Kitts & Nevis", id: 225 },
{ name: "St. Lucia", id: 230 },
{ name: "St. Vincent & Grenadinen", id: 224 },
{ name: "Sudan", id: 160 },
{ name: "Suriname", id: 161 },
{ name: "Swaziland", id: 273 },
{ name: "Sweden", id: 147 },
{ name: "Switzerland", id: 148 },
{ name: "Syria", id: 163 },
{ name: "Tahiti", id: 237 },
{ name: "Tajikistan", id: 165 },
{ name: "Tanzania", id: 166 },
{ name: "Thailand", id: 167 },
{ name: "The Gambia", id: 52 },
{ name: "Tibet", id: 245 },
{ name: "Togo", id: 168 },
{ name: "Tonga", id: 169 },
{ name: "Trinidad and Tobago", id: 170 },
{ name: "Tunisia", id: 173 },
{ name: "Turkey", id: 174 },
{ name: "Turkmenistan", id: 175 },
{ name: "Turks- and Caicosinseln", id: 226 },
{ name: "Tuvalu", id: 247 },
{ name: "UdSSR", id: 221 },
{ name: "Uganda", id: 176 },
{ name: "Ukraine", id: 177 },
{ name: "United Arab Emirates", id: 183 },
{ name: "United Kingdom", id: 264 },
{ name: "United States", id: 184 },
{ name: "Uruguay", id: 179 },
{ name: "Uzbekistan", id: 180 },
{ name: "Vanuatu", id: 181 },
{ name: "Vatican", id: 256 },
{ name: "Venezuela", id: 182 },
{ name: "Vietnam", id: 185 },
{ name: "Wales", id: 191 },
{ name: "Western Sahara", id: 275 },
{ name: "Yemen", id: 186 },
{ name: "Yugoslavia (Republic)", id: 258 },
{ name: "Zaire", id: 254 },
{ name: "Zambia", id: 142 },
{ name: "Zanzibar", id: 253 },
{ name: "Zimbabwe", id: 187 }];